/*
PeerTube

Testing VideoFeedsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk

import (
	"context"
	openapiclient "github.com/RustLangLatam/peertube_api_sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_VideoFeedsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VideoFeedsAPIService GetSyndicatedComments", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var format string

		resp, httpRes, err := apiClient.VideoFeedsAPI.GetSyndicatedComments(context.Background(), format).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoFeedsAPIService GetSyndicatedSubscriptionVideos", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var format string

		resp, httpRes, err := apiClient.VideoFeedsAPI.GetSyndicatedSubscriptionVideos(context.Background(), format).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoFeedsAPIService GetSyndicatedVideos", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var format string

		resp, httpRes, err := apiClient.VideoFeedsAPI.GetSyndicatedVideos(context.Background(), format).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoFeedsAPIService GetVideosPodcastFeed", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.VideoFeedsAPI.GetVideosPodcastFeed(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
