/*
PeerTube

Testing VideoTranscodingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk_go

import (
	"context"
	"github.com/RustLangLatam/peertube_api_sdk_go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_go_VideoTranscodingAPIService(t *testing.T) {

	configuration := api.NewConfiguration()
	apiClient := api.NewAPIClient(configuration)

	t.Run("Test VideoTranscodingAPIService CreateVideoTranscoding", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id ApiV1VideosOwnershipIdAcceptPostIdParameter

		httpRes, err := apiClient.VideoTranscodingAPI.CreateVideoTranscoding(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
