/*
PeerTube

Testing MyNotificationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk_go

import (
	"context"
	"github.com/RustLangLatam/peertube_api_sdk_go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_go_MyNotificationsAPIService(t *testing.T) {

	configuration := api.NewConfiguration()
	apiClient := api.NewAPIClient(configuration)

	t.Run("Test MyNotificationsAPIService ApiV1UsersMeNotificationSettingsPut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MyNotificationsAPI.ApiV1UsersMeNotificationSettingsPut(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyNotificationsAPIService ApiV1UsersMeNotificationsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MyNotificationsAPI.ApiV1UsersMeNotificationsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyNotificationsAPIService ApiV1UsersMeNotificationsReadAllPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MyNotificationsAPI.ApiV1UsersMeNotificationsReadAllPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyNotificationsAPIService ApiV1UsersMeNotificationsReadPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MyNotificationsAPI.ApiV1UsersMeNotificationsReadPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
