/*
PeerTube

Testing VideoBlocksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk

import (
	"context"
	openapiclient "github.com/RustLangLatam/peertube_api_sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_VideoBlocksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VideoBlocksAPIService AddVideoBlock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id openapiclient.ApiV1VideosOwnershipIdAcceptPostIdParameter

		httpRes, err := apiClient.VideoBlocksAPI.AddVideoBlock(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoBlocksAPIService DelVideoBlock", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var id openapiclient.ApiV1VideosOwnershipIdAcceptPostIdParameter

		httpRes, err := apiClient.VideoBlocksAPI.DelVideoBlock(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoBlocksAPIService GetVideoBlocks", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.VideoBlocksAPI.GetVideoBlocks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
