/*
PeerTube

Testing InstanceRedundancyAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk

import (
	"context"
	openapiclient "github.com/RustLangLatam/peertube_api_sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_InstanceRedundancyAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InstanceRedundancyAPIService ApiV1ServerRedundancyHostPut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var host string

		httpRes, err := apiClient.InstanceRedundancyAPI.ApiV1ServerRedundancyHostPut(context.Background(), host).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
