/*
PeerTube

Testing MyHistoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk_go

import (
	"context"
	"github.com/RustLangLatam/peertube_api_sdk_go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_go_MyHistoryAPIService(t *testing.T) {

	configuration := api.NewConfiguration()
	apiClient := api.NewAPIClient(configuration)

	t.Run("Test MyHistoryAPIService ApiV1UsersMeHistoryVideosGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MyHistoryAPI.ApiV1UsersMeHistoryVideosGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyHistoryAPIService ApiV1UsersMeHistoryVideosRemovePost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MyHistoryAPI.ApiV1UsersMeHistoryVideosRemovePost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MyHistoryAPIService ApiV1UsersMeHistoryVideosVideoIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var videoId int32

		httpRes, err := apiClient.MyHistoryAPI.ApiV1UsersMeHistoryVideosVideoIdDelete(context.Background(), videoId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
