/*
PeerTube

Testing MySubscriptionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk

import (
	"context"
	openapiclient "github.com/RustLangLatam/peertube_api_sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_MySubscriptionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MySubscriptionsAPIService ApiV1UsersMeSubscriptionsExistGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MySubscriptionsAPI.ApiV1UsersMeSubscriptionsExistGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MySubscriptionsAPIService ApiV1UsersMeSubscriptionsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MySubscriptionsAPI.ApiV1UsersMeSubscriptionsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MySubscriptionsAPIService ApiV1UsersMeSubscriptionsPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MySubscriptionsAPI.ApiV1UsersMeSubscriptionsPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MySubscriptionsAPIService ApiV1UsersMeSubscriptionsSubscriptionHandleDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var subscriptionHandle string

		httpRes, err := apiClient.MySubscriptionsAPI.ApiV1UsersMeSubscriptionsSubscriptionHandleDelete(context.Background(), subscriptionHandle).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MySubscriptionsAPIService ApiV1UsersMeSubscriptionsSubscriptionHandleGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var subscriptionHandle string

		resp, httpRes, err := apiClient.MySubscriptionsAPI.ApiV1UsersMeSubscriptionsSubscriptionHandleGet(context.Background(), subscriptionHandle).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MySubscriptionsAPIService ApiV1UsersMeSubscriptionsVideosGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.MySubscriptionsAPI.ApiV1UsersMeSubscriptionsVideosGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
