/*
PeerTube

Testing VideoMirroringAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk

import (
	"context"
	openapiclient "github.com/RustLangLatam/peertube_api_sdk"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_VideoMirroringAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VideoMirroringAPIService DelMirroredVideo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var redundancyId string

		httpRes, err := apiClient.VideoMirroringAPI.DelMirroredVideo(context.Background(), redundancyId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoMirroringAPIService GetMirroredVideos", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.VideoMirroringAPI.GetMirroredVideos(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VideoMirroringAPIService PutMirroredVideo", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.VideoMirroringAPI.PutMirroredVideo(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
