/*
PeerTube

Testing RegisterAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk_go

import (
	"context"
	"github.com/RustLangLatam/peertube_api_sdk_go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_go_RegisterAPIService(t *testing.T) {

	configuration := api.NewConfiguration()
	apiClient := api.NewAPIClient(configuration)

	t.Run("Test RegisterAPIService AcceptRegistration", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var registrationId int32

		httpRes, err := apiClient.RegisterAPI.AcceptRegistration(context.Background(), registrationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService DeleteRegistration", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var registrationId int32

		httpRes, err := apiClient.RegisterAPI.DeleteRegistration(context.Background(), registrationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService ListRegistrations", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RegisterAPI.ListRegistrations(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService RegisterUser", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.RegisterAPI.RegisterUser(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService RejectRegistration", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var registrationId int32

		httpRes, err := apiClient.RegisterAPI.RejectRegistration(context.Background(), registrationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService RequestRegistration", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RegisterAPI.RequestRegistration(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService ResendEmailToVerifyRegistration", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.RegisterAPI.ResendEmailToVerifyRegistration(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RegisterAPIService VerifyRegistrationEmail", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var registrationId int32

		httpRes, err := apiClient.RegisterAPI.VerifyRegistrationEmail(context.Background(), registrationId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
