/*
PeerTube

Testing RunnerRegistrationTokenAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk_go

import (
	"context"
	"github.com/RustLangLatam/peertube_api_sdk_go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_go_RunnerRegistrationTokenAPIService(t *testing.T) {

	configuration := api.NewConfiguration()
	apiClient := api.NewAPIClient(configuration)

	t.Run("Test RunnerRegistrationTokenAPIService ApiV1RunnersRegistrationTokensGeneratePost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.RunnerRegistrationTokenAPI.ApiV1RunnersRegistrationTokensGeneratePost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerRegistrationTokenAPIService ApiV1RunnersRegistrationTokensGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.RunnerRegistrationTokenAPI.ApiV1RunnersRegistrationTokensGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RunnerRegistrationTokenAPIService ApiV1RunnersRegistrationTokensRegistrationTokenIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var registrationTokenId int32

		httpRes, err := apiClient.RunnerRegistrationTokenAPI.ApiV1RunnersRegistrationTokensRegistrationTokenIdDelete(context.Background(), registrationTokenId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
