/*
PeerTube

Testing ServerBlocksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package peertube_api_sdk_go

import (
	"context"
	"github.com/RustLangLatam/peertube_api_sdk_go/api"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_peertube_api_sdk_go_ServerBlocksAPIService(t *testing.T) {

	configuration := api.NewConfiguration()
	apiClient := api.NewAPIClient(configuration)

	t.Run("Test ServerBlocksAPIService ApiV1ServerBlocklistServersGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerBlocksAPI.ApiV1ServerBlocklistServersGet(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerBlocksAPIService ApiV1ServerBlocklistServersHostDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var host string

		httpRes, err := apiClient.ServerBlocksAPI.ApiV1ServerBlocklistServersHostDelete(context.Background(), host).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerBlocksAPIService ApiV1ServerBlocklistServersPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerBlocksAPI.ApiV1ServerBlocklistServersPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
